import { Reference } from '~types';
import Joi from '@hapi/joi';

export function createReferenceConnection(meta = {}) {
  return {
    meta: {
      // We use the meta ID generated by jsPlumb
      ...meta,
      type: Reference,
      name: 'Reference'
    },
    config: {
      id: '',
      allows: ''
      // We don't immediately grab the source and target. We will grab it when we pack the configuration to send
      // to the deployment server. This helps us avoid state inconsitencies and complext update logic when resources
      // are updated after connections have been made.
    }
  };
}

const idSchema = Joi.string()
  .alphanum()
  .error(new Error('Reference ID must only contain alphanumeric characters'));

export function validateId(val) {
  const { error } = idSchema.validate(val);
  if (error) return error.message;
  return '';
}

