import { Reference } from '~types';

export function createReferenceConnection(source, target, meta = {}) {
  return {
    meta: {
      // We use the meta ID generated by jsPlumb
      ...meta,
      type: Reference,
      name: 'Reference'
    },
    config: {
      id: '',
      type: '',
      source,
      target
    }
  };
}
