import { Trigger } from '~types';

export function createTriggerConnection(source, target, meta = {}) {
  return {
    meta: {
      // We use the meta ID generated by jsPlumb
      ...meta,
      type: Trigger,
      name: 'Trigger'
    },
    config: {
      source,
      target
    }
  };
}
